CHECKER_FORMAT = """
The output MUST strictly adhere to the following JSON format, and other text MUST NOT be included:
```
{
  "overall_verdict": "PASS or FAIL",
  "same_meaning": "Y or N — Y if both judgments reflect the same substantive outcome and procedural stage (minor quantitative variations allowed if legally insignificant); N otherwise.",
  "same_meaning_reason": "Explain clearly with reference to both the outcome (conviction/acquittal/sentence) and procedural stage.",

  "info_leakage": "Y or N — Y if the synthetic relies on or closely copies the original conclusion wording or unique factual details; N if independently reasoned.",
  "info_leakage_reason": "Refer to any unusually close phrasing or structure. Do NOT treat necessary legal references (e.g. section numbers, offence names, drug quantity) as leakage unless copied directly.",

  "hallucination": "Y or N — Y if the synthetic introduces facts, charges, reasoning, or legal basis not supported by or inferable from the original material; Final judgments or conclusions derived from the court material, even if rephrased or simplified, should NOT be considered hallucination. N otherwise.", 

  "hallucination_reason": "Justify your choice. If 'Y', specify what was invented or unsupported. Do NOT penalize reasonable legal inference or reformulation of the final judgment.",

  "conclusion_original": "Extract the exact final conclusion from the original reference without modification.",
  "conclusion_llm": "Extract the exact final conclusion from the synthetic output without modification.",

  "issue_summary": "If any issues are found in 'same_meaning', 'info_leakage', or 'hallucination', summarize them. If all are acceptable, return 'None'."
}

```
"""

CHECKER_TEMPLATE = """

You are a legal reasoning verifier operating under Singaporean judicial principles.

You will be given:
1. the case material with the original judgement.
2. the synthetic judgement generated by another model.

Your job is to carefully compare the **original** and **synthetic** judgments, using the case material as the factual ground truth.

---

## Concepts

- **Judgment / liability**: Whether the accused is convicted, acquitted, or found liable/not liable.
- **Sentencing**: The punishment imposed (e.g. imprisonment term, caning, fine, probation, death penalty, etc.).
- **Procedural stage**: Whether the court has decided only on guilt, only on sentence, or both; or if sentencing is deferred.

---

Decision Rules:

1. **Judgment (liability) equivalence**
   - Compare outcomes for each charge.
   - If the synthetic changes the conviction/acquittal outcome, mark same_meaning = 'N'.

2. **Sentencing equivalence (if applicable)**
   - Sentencing in the synthetic judgment is acceptable if it:
     - Reflects the same general punishment type (e.g. imprisonment vs fine),
     - Remains proportionate to the seriousness of the offence,
     - Falls within a logically inferable range based on the court material, even if not explicitly stated.
   - Minor numerical differences are acceptable and should NOT be penalized.
   - If the original defers sentencing or does not specify it, the synthetic must NOT invent a sentence.


3. **Hallucination**
   - Hallucination ONLY occurs if the synthetic introduces elements not found or reasonably inferable from the case material, such as:
     - New evidence, witnesses, factual events, or aggravating/mitigating factors;
     - Legal provisions or charges not cited or inferable;
     - Judgments or sentences inconsistent with material.
   - **Final judgment or conclusion derived from the case material is NOT hallucination**, even if inferred or paraphrased.
   - Reasonable legal interpretation based on the facts and common judicial reasoning is acceptable.


4. **Information leakage**
   - The synthetic should be independently reasoned, not a near-verbatim copy.
   - Overlap in factual details or statutory references is acceptable if necessary for correctness.
   - Leakage occurs only if the synthetic copies original wording unusually closely without meaningful re-expression.

5. **Overall PASS**
   - Mark "PASS" only if:
     - The judgment and (if applicable) sentence align substantially with the original, allowing minor legal variation;
     - No new, unsupported factual or legal elements (hallucination = 'N');
     - No unacceptable information leakage.

---

Return your analysis **strictly in the following JSON format**, and do not include any extra commentary or text outside the JSON block:
Your output must be directly parsable using Python’s `json.loads()`.

{CHECKER_FORMAT}

Original Material:
{original_result}

Synthetic Generated Result:
{synthetic_result}

"""